title: admin-as-service example
url: '${API_URL}'
apiType: json-server
fileUploadURL: http://example.com/upload
basePath: /
messages:
  dashboard: Hello world!
numeral:
  currency:
    symbol: €
  delimiters:
    thousands: ' '
    decimal: ','
auth:
  grantType: dummy #use password for username/password credentials
  authorizeUrl: https://auth.example.com/oauth/token
  clientId: client_id
  clientSecret: client_secret
  scope: accounts
entities:
  posts:
    name: My Post
    # endpoint: "posts?blah=foo"
    endpoint: "posts"
    identifier: id
    list:
      listActions:
        - title: redirect for {{values.title}}
          action: redirect
          url: 'https://www.google.cz/?ei={{values.id}}&blah={{values.title}}&firstname={{values.user_firstname}}&access_token={{auth.access_token}}'
          target: blank
      title: My custom posts title
      filters:
        fields:
          - attribute: q
            label: Search
            pinned: true
            attributes:
              placeholder: search text
              searchColumns: title
          - attribute: user_id
            label: User
            type: reference
            entity: users
            template: "{{firstname}} {{lastname}}"
          - attribute: active
            label: Active
            type: boolean
          - attribute: states
            type: choices
            options:
              - value: US
                label: USA
              - value: FR
                label: France
    create:
      actions:
        - list
      title: My custom posts create title
    edit:
      actions:
        - delete
        - list
      title: My custom posts edit title
      fieldsets:
        - title: Basic data
          description: Description of section
          hidden: false
          expanded: true
          fields:
            - attribute: title
              label: Post title
            - attribute: active
              label: Active
              type: boolean
            - attribute: states
              type: choices
              required: true
              options:
                - value: US
                  label: USA
                - value: FR
                  label: France
            - attribute: state
              type: choice
              required: true
              options:
                - value: US
                  label: USA
                - value: FR
                  label: France 
            - attribute: user_id
              label: User
              type: reference
              entity: users
              template: "{{firstname}} {{lastname}}"
    fields:
      - attribute: title
        label: Post title
        main: true
      - attribute: active
        label: Active
        type: boolean
      - attribute: states
        type: choices
        required: true
        options:
          - value: US
            label: USA
          - value: FR
            label: France
      - attribute: user_id
        label: User
        type: reference
        toMany: false
        entity: users
        template: "{{firstname}} {{lastname}}"
        targetField: firstname
      - attribute: user_firstname
        foreignKey: user_id
        label: User
        type: reference
        entity: users
        template: "{{firstname}}"
  users:
    name: User
    hidden: false
    fields:
      - attribute: firstname
      - attribute: lastname
      - attribute: email
        type: email
        required: true
      - attribute: salary
        type: float
        step: 0.1
      - attribute: notes
        type: text
      - attribute: birthdate
        type: date
      - attribute: lastVisit
        type: datetime
      - attribute: wakeupTime
        type: time
      - attribute: document
        type: file
    list:
      fields:
        - attribute: firstname
          main: true
        - attribute: lastname
          main: true
        - attribute: salary
          type: float
          format: '$0,0.00'
    edit:
      title: User Edit title
      tabtitle: Basic info
      tabs:
        - title: Posts Tab
          itemTitle: '{{title}} {{active?"active":"inactive"}} {{moment().format("lll")}} {{numeral(123032542).format("$0,0.0")}}'
          order: active
          reference:
            entity: posts
            attribute: user_id
          fields:
            - attribute: title
            - attribute: active
              label: Active
              type: boolean
  hidden:
    name: Hidden entity
    hidden: true

