title: Adminr example
url: ${API_URL}
# url: https://jsonplaceholder.typicode.com
# oauth:
#   flow: resourceOwnerPasswordCredentials
#   authorizeUrl: https://api.example.com/authorize
entities:
  posts:
    name: My Post
    list:
      title: My custom posts title
      filters:
        q:
          label: Search
          pinned: true
    create:
      title: My custom posts create title
    edit:
      title: My custom posts edit title
    fields:
      - attribute: title
      - attribute: state
        type: select
        options:
          - { value: US, label: USA }
          - { value: FR, label: France }
      - attribute: userId
        type: reference
        toMany: false
        entity: users
        targetField: name
  users:
    name: User
    fields:
      - attribute: firstname
      - attribute: lastname
      - attribute: email
    list:
      fields:
        - attribute: firstname
        - attribute: lastname
