title: admin-as-service example
url: '${API_URL}'
entities:
  posts:
    name: My Post
    endpoint: "posts"
    identifier: id
    list:
      listActions:
        - title: test
          icon: new-window
          action: redirect
          url: 'https://www.google.cz/?ei={{entry.values.id}}'
          target: blank
        - edit
        - delete
      actions:
        - create
        - export
        - filter
      title: My custom posts title
      filters:
        q:
          label: Search
          pinned: true
          attributes:
            placeholder: search text
            searchColumns: title
        'where[user_id]':
          label: User
          type: reference
          entity: users
          targetField: firstname
    create:
      actions:
        - list
      title: My custom posts create title
    edit:
      actions:
        - delete
        - list
      title: My custom posts edit title
    fields:
      - attribute: title
      - attribute: state
        type: choice
        options:
          - value: US
            label: USA
          - value: FR
            label: France
      - attribute: user_id
        type: reference
        toMany: false
        entity: users
        targetField: firstname
  users:
    name: User
    readonly: true
    fields:
      - attribute: firstname
      - attribute: lastname
      - attribute: email
      - attribute: salary
        type: float
    list:
      fields:
        - attribute: firstname
        - attribute: lastname
        - attribute: salary
          type: float
          format: '$0,0.00'
