title: admin-as-service example
url: ${API_URL}
# url: https://jsonplaceholder.typicode.com
# oauth:
#   flow: resourceOwnerPasswordCredentials
#   authorizeUrl: https://api.example.com/authorize
entities:
  posts:
    name: My Post
    list:
      title: My custom posts title
      filters:
        q:
          label: Search
          pinned: true
          attributes:
            placeholder: search text
            searchColumns: title
        where[user_id]:
          label: User
          type: reference
          entity: users
          targetField: firstname
    create:
      title: My custom posts create title
    edit:
      title: My custom posts edit title
    fields:
      - attribute: title
      - attribute: state
        type: select
        options:
          - { value: US, label: USA }
          - { value: FR, label: France }
      - attribute: user_id
        type: reference
        toMany: false
        entity: users
        targetField: firstname
  users:
    name: User
    fields:
      - attribute: firstname
      - attribute: lastname
      - attribute: email
    list:
      fields:
        - attribute: firstname
        - attribute: lastname
