title: Onewordapp admin
url: https://api.onewordapp.io/v1
oauth:
  flow: resourceOwnerPasswordCredentials
  authorizeUrl: https://api.onewordapp.io/v1/authorize
entities:
  words:
    name: Word
    list:
      fields:
        - name: uid
        - name: index
        - name: name
    create:
      fields:
        - name: uid
    edit:
      fields:
        - name: uid
        - name: name
        - name: pronunciation
        - name: description
          type: text
        - name: example
          type: text
        - name: audioURL
