title: Adminr example
url: ${API_URL}
# url: https://jsonplaceholder.typicode.com
# oauth:
#   flow: resourceOwnerPasswordCredentials
#   authorizeUrl: https://api.example.com/authorize
entities:
  posts:
    name: Post
    list:
      fields:
        - attribute: title
        - attribute: userId
          type: reference
          toMany: false
          entity: users
          targetField: name
    create:
      fields:
        - attribute: title
        - attribute: userId
          type: reference
          toMany: false
          entity: users
          targetField: name
    edit:
      fields:
        - attribute: title
        - attribute: userId
          type: reference
          toMany: false
          entity: users
          targetField: name
  users:
    name: User
    list:
      fields:
        - attribute: name
        - attribute: username
        - attribute: email
    create:
      fields:
        - attribute: name
        - attribute: username
        - attribute: email
    edit:
      fields:
        - attribute: name
        - attribute: username
        - attribute: email
