title: Adminr example
url: ${API_URL}
# url: https://jsonplaceholder.typicode.com
# oauth:
#   flow: resourceOwnerPasswordCredentials
#   authorizeUrl: https://api.example.com/authorize
entities:
  posts:
    name: My Post
    fields:
      - attribute: title
      - attribute: userId
        type: reference
        toMany: false
        entity: users
        targetField: name
  users:
    name: User
    fields:
      - attribute: name
      - attribute: username
      - attribute: email
    list:
      fields:
        - attribute: name
        - attribute: username
