title: Adminr example
url: https://jsonplaceholder.typicode.com
# oauthFlow: resourceOwnerPasswordCredentials
entities:
  posts:
    name: Post
    list:
      fields:
        - name: title
        - name: userId
          type: reference
          toMany: false
          entity: users
          targetField: name
    create:
      fields:
        - name: title
        - name: userId
          type: reference
          toMany: false
          entity: users
          targetField: name
    edit:
      fields:
        - name: title
        - name: userId
          type: reference
          toMany: false
          entity: users
          targetField: name
  users:
    name: User
    list:
      fields:
        - name: name
        - name: username
        - name: email
    create:
      fields:
        - name: name
        - name: username
        - name: email
    edit:
      fields:
        - name: name
        - name: username
        - name: email
